export const actions = {
  GET_CAROUSEL_ITEMS: 'GET_CAROUSEL_ITEMS',
  GET_CATEGORY_DATA: 'GET_CATEGORY_DATA',
  GET_PRODUCTS_DATA: 'GET_PRODUCTS_DATA',
  OPEN_CART: 'OPEN_CART',
  UPDATE_TO_CART: 'UPDATE_TO_CART'
};